services:
  twitter-auto-generator:
    build: .
    ports:
      - "3000:80"
    environment:
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_KEY_SECRET=${TWITTER_API_KEY_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - HASHED_PASSWORD=${HASHED_PASSWORD}